### ISSUE TITLE
Heroku deployment not working from GET STARTED

### ISSUE THREAD

**Issue by ShotaMegre** [electrode-io/electrode#221] opened 2017-03-04 04:52 UTC
Seems documentation is behind of the current development.
There are plenty of changes in the project that differs from the Get Started Instructions (for example having everything packed under "/src" folder instead of just "/client, /server".
Also, following the instructions to deploy the project to Heroku, the app crashes.
It's not an issue related to latest nodejs/npm, as I've tried the same with NodeJS 6.10.0/npm 3.10.10.

Code from package.json:
```
"engines": {
    "node": "7.7.1",
    "npm": "4.1.2"
  }
```

The log dump from Heroku:
```
2017-03-04T04:51:54.298889+00:00 app[web.1]: > echo 'Starting standalone server in PROD mode'; node .
2017-03-04T04:51:54.298890+00:00 app[web.1]: 
2017-03-04T04:51:54.303678+00:00 app[web.1]: Starting standalone server in PROD mode
2017-03-04T04:51:54.351562+00:00 app[web.1]: module.js:472
2017-03-04T04:51:54.351566+00:00 app[web.1]:     throw err;
2017-03-04T04:51:54.351566+00:00 app[web.1]:     ^
2017-03-04T04:51:54.351567+00:00 app[web.1]: 
2017-03-04T04:51:54.351568+00:00 app[web.1]: Error: Cannot find module '/app'
```

**Comment by SampsonCrowley** [comment] 2017-03-06 03:10
The problem is where it looks for the server, I don't know what the hell is going on with what they've set up but it doesn't even run a gulp build

in the scripts section of package.json, add a script `"prestart": "gulp build"`
and change `"prod": "echo 'Starting standalone server in PROD mode'; node .",`
to `"prod": "echo 'Starting standalone server in PROD mode'; node ./lib/server/"`

**Comment by SampsonCrowley** [comment] 2017-03-06 03:12
they are also dropping the ball on where the app looks for static files. it's a blemish on what is otherwise a great generator

**Comment by SampsonCrowley** [comment] 2017-03-06 03:26
I've made a pull request that will fix things until they're up to date

**Comment by SampsonCrowley** [comment] 2017-03-06 04:24
@ShotaMegre
The problem is where it looks for the server, I don't know what the hell is going on with what they've set up but it doesn't even run a gulp build

in package.json change the scripts section to:

`"scripts": {
    "prestart": "gulp build",
    "start": "if test \"$NODE_ENV\" = \"production\"; then npm run prod; else gulp dev; fi",
    "test": "gulp check",
    "coverage": "gulp check",
    "prod": "echo 'Starting standalone server in PROD mode'; node ./lib/server/",
    "heroku-postbuild": "gulp build"
  },`

in the {express | koa}-server.js change the set static path to hav '../..':
`path.join(__dirname, "../..",
    defaultConfig.$("plugins.electrodeStaticPaths.options.pathPrefix"))`

**Comment by SampsonCrowley** [comment] 2017-03-10 02:44
I just notice I left the heroku-postbuild in my comment above, You will want to remove that, there is no need for it with the prestart

**Comment by animesh10** [comment] 2017-04-04 18:53
Merged and fixed by: https://github.com/electrode-io/electrode/pull/224

**Closed** 2017-06-23 06:07 UTC
Labels: answered
