### ISSUE TITLE
electrode X fails to load isomorphic-assets

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1547] opened 2020-03-05 21:29 UTC
## Type of issue

bug :bug:

## My environment

- OS version/details: osx, mojave
- Node version: 12
- npm version: 6
- Version of yo : n/a

## Expected behavior

- no isomorphic-config error

## Current behavior

`npx clap dev` starts, yet @ http://localhost:2992/__electrode_dev/log, one sees an isomorphic configuration error

## Steps to reproduce the behavior

```
npx clap dev
```

## Command line output

```
info: Hapi.js server running at http://m-c02x6042jgh7:3100
info: 
info: > isomorphic-loader extend require: config is INVALID!! - webpack dev server mode - waiting <
info: reload isomorphic assets failed [Error: ENOENT: no such file or directory, open '/Users/c0d01a5/src/storks/.isomorphic-loader-config.json'] {
info: errno: -2,
info: code: 'ENOENT',
info: syscall: 'open',
info: path: '/Users/c0d01a5/src/storks/.isomorphic-loader-config.json'
info: }
```

## discussion

wasn't this moved from disk to IPC, recently?  is this possibly a regression?

**Comment by divyakarippath** [comment] 2020-04-27 21:35
Hi @cdaringe, is this issue still reproducible for you? If so, could you please share your repo details. I can try to reproduce it there.
Looks like the issue is been resolved in newly created apps.

**Comment by cdaringe** [comment] 2020-04-28 00:34
The lack of reproducqbility of this problem is in fact a key part of the problem. Unfortunately I can't just give you a prescription on how to reproduce it, I can only say " use electrode " regularly and you will run into it. this one we shouldn't close, and I think given the fact that I've seen this in every single electrode project I've worked on, probably needs a reevaluation of the pipeline and a study on the reliability around the offending error / code path

**Comment by jchip** [comment] 2020-04-28 02:29
Many versions ago, Electrode app in dev mode was communicating with webpack dev server through the file system with lockfile etc, and it was very messy so there were always timing corner cases that cause issues.

Electrode has switched to using IPC through `process.send` since the addition of the dev-admin, and it doesn't even use the `.isomorphic-loader-config.json` anymore.

If you still run into this problem, please check the version of the `electrode-archetype-react-app` and if dev-admin is used.

Electrode X has even more improvements and fixes to the dev admin and this problem should definitively fixed.

**Closed** 2020-07-21 20:06 UTC
Labels: fixed
