### ISSUE TITLE
subapp-server crashes on ui code change

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1607] opened 2020-04-20 18:26 UTC
## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

n/a ^

## Expected behavior

no crash

## Current behavior

crash

## Steps to reproduce the behavior

- follow https://gecgithub01.walmart.com/pages/electrode/docs/getting-started, install new EX app 
- `npx clap dev`
- update `src/ui/**` code
- observe server crash with above error message

```
$ cat node_modules/subapp-server/package.json | jq .version
"1.1.17"
```

## Command line output

```
info: registerSubApp: subapp 'Home' already registered - replacing
info: registerSubApp: subapp 'Demo1' already registered - replacing
error: Route / failed: Error: Cannot wrap an error
error:     at new module.exports (/Users/c0d01a5/src/smarties/node_modules/@hapi/hoek/lib/error.js:23:19)
info:     at Object.module.exports [as assert] (/Users/c0d01a5/src/smarties/node_modules/@hapi/hoek/lib/assert.js:20:11)
info:     at internals.Toolkit.response (/Users/c0d01a5/src/smarties/node_modules/@hapi/hapi/lib/toolkit.js:174:14)
info:     at handler (/Users/c0d01a5/src/smarties/node_modules/subapp-server/lib/setup-hapi-routes.js:190:20)
info:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cdaringe** [comment] 2020-04-20 18:38
related, but independently addressable issue:

```
Error: at ./node_modules/subapp-web/lib/load.js
Error: SSR subapp Home failed
TypeError: Cannot read property 'entryPoints' of undefined
    at prepareSubAppSplitBundles (./node_modules/subapp-web/lib/load.js:144:32)
    at processSubapp (./node_modules/subapp-web/lib/load.js:332:44)
    at asyncProcess (./node_modules/subapp-web/lib/load.js:385:17)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

![image](https://user-images.githubusercontent.com/1003261/79787147-66200c80-82fb-11ea-9108-60950cdf2b05.png)

**Comment by divyakarippath** [comment] 2020-04-27 20:16
@cdaringe Looks like the issue is been fixed in latest versions. I am unable to reproduce this when I create a new app. Could you share your repo details please? I can try to reproduce the issue there and figure out the updates needed to fix it.

**Comment by cdaringe** [comment] 2020-04-28 00:32
Hello! Indeed my repository was ephemeral. I created it ran into the issue and removed it. Feel free to close if you cannot reproduce, I'll file another ticket if it happens again

**Closed** 2020-07-21 20:07 UTC
Labels: fixed
