### ISSUE TITLE
Production bundle errors

### ISSUE THREAD

**Issue by jlim81** [electrode-io/electrode#88] opened 2016-12-21 08:19 UTC
There is either a problem building the production bundle, or pathing to the correct files are broken.

Running `npm run prod` results in path errors  when loading `style.*.css`, as well as `bundles.*.css` From loading the main page of the boilerplate.

Running `gulp build`, then `npm run prod` seemingly generates the bundles, but the bundles (css & js) are both empty, with what looks to be the contents of index.html

**Comment by RicciOne** [comment] 2017-01-07 22:24
I am having the same issue! I have been trying to figure this out for a week, but unfortunately have found no answers on this issue. Dev mode is incredible!!! But, now I'm trying to deploy to AWS and can't get production to work. Please, help! :) Thanks!

**Comment by oliwerhelsen** [comment] 2017-01-09 21:57
Yeah i'm also getting this problem when deploying to Heroku. Anyone that has found a solution?:)

**Comment by RicciOne** [comment] 2017-01-09 23:52
Not yet! I've looked for over a week and found nothing.

**Comment by oliwerhelsen** [comment] 2017-01-10 07:06
Maybe @animesh10 knows something about this?

**Comment by animesh10** [comment] 2017-01-10 19:23
@oliwerhelsen @RicciOne ,
I am able to deploy our sample generated app on heroku, following the instructions. Heroku does default to production env, and our package.json will accommodate that.

Are you successfully able to run it in Production mode on your local? Meanwhile, i'll go ahead and try out aws.

**Comment by jlim81** [comment] 2017-01-10 20:29
@animesh10 Regardless of deployment environment, it should be able to generate a production optimized bundle. I have tried setting the NODE_ENV explicitly as part of the start script, but it does not work. What else is missing?

**Comment by animesh10** [comment] 2017-01-10 20:32
And this is only happening on AWS?

**Comment by jlim81** [comment] 2017-01-10 20:32
I can't generate a production bundle using npm run prod locally.

**Comment by oliwerhelsen** [comment] 2017-01-10 20:34
Same for me:-(

**Comment by oliwerhelsen** [comment] 2017-01-10 20:46
I just generated a new instance of Electrode with ExpressJS with Yeoman and deployed it to Heroku. It didin't work. I keep getting: Uncaught SyntaxError: Unexpected token <

**Comment by RicciOne** [comment] 2017-01-10 21:21
Hi Animesh! Thank you for responding! Yes, this is happening on AWS, but also happening on local environment. I've tried everything from gulp pwa to NODE_ENV=production npm run prod. It looks like it's building properly, but the bundle isn't being served. In dev, the bundle is served with webpack on port 2992. But, in prod it looks for it under 3000 and it's not there.

**Comment by animesh10** [comment] 2017-01-11 01:26
Hi @RicciOne , could you let me know what your node, npm, yo versions are. 
I am using node@v6.9.1, npm@3.10.8 and yo@1.8.5. The app generates and successfully runs for me.

@oliwerhelsen : I see the error with express on heroku and will take a look.

**Comment by oliwerhelsen** [comment] 2017-01-11 05:39
You're the best. Thanks!

**Comment by RicciOne** [comment] 2017-01-11 13:31
@animesh10 I recently upgraded to node 7.0.0. I'm using npm 3.10.8, and yo 1.8.4

**Comment by animesh10** [comment] 2017-01-12 21:45
@RicciOne , I tried with the above node/npm and yo versions on the generated app with HapiJS server. It does work for me. Are you running `gulp build` before you do an `npm run prod` ?

**Comment by RicciOne** [comment] 2017-01-15 07:34
@animesh10 , I ran gulp build and npm run prod, and can see the application running on port 3000, however none of the javascript or css is loading. When I click the buttons on the sample application, the value remains at "999". It appears the application is unable to access the js and css bundles.

**Comment by RicciOne** [comment] 2017-01-17 00:10
@animesh10 Hapi works fine in production. My problem is specific to Express.

**Comment by Nickersona** [comment] 2017-02-01 19:14
Any Update on this issue? I just ran a test generating a fresh project from yeoman using a HapiJS  server and an Express server (disabled everything else in the generator).  Running `gulp build; gulp server` for each. HapiJS  works as intended, while the generated Express app has the same issues @riccijs mentions above.

Here's the output I'm getting in the dev console for the failing express server.
<img width="722" alt="console" src="https://cloud.githubusercontent.com/assets/544287/22522099/40677c0a-e86f-11e6-82bd-37244eff468e.png">
<img width="715" alt="source" src="https://cloud.githubusercontent.com/assets/544287/22522098/40648edc-e86f-11e6-9da3-df5d011c287e.png">

The express dev server works fine, Seems to just be the Express prod server which is failing.

**Comment by Nickersona** [comment] 2017-02-01 23:10
OK after looking at the error for a while and sifting through the Express code, my guess to the source was that the the server wasn't registering it's static asset path correctly.  Seems like the server is routing all requests (including requests to your js bundle) to index view setup by `electrode-react-webapp` package. Thats why your bundle seems to return an HTML file.

So a workaround I found was to update the static path in the `/server/express-server.js` file from
``` javascript
const setStaticPaths = function () {
  app.use(express.static(path.join(__dirname,
    defaultConfig.$("plugins.electrodeStaticPaths.options.pathPrefix"))));
};
```
to 
``` javascript
const setStaticPaths = function () {
  app.use(express.static(path.join(__dirname, '../', // <--- Move up one dir
    defaultConfig.$("plugins.electrodeStaticPaths.options.pathPrefix"))));
};
```

The server was looking in `/server/dist` for assets when it should just be /dist. This causes some errors to be thrown by the service worker code generated by yeoman, but we didn't need that so I removed it and it's running without errors. Still working on getting it to Heroku, but this should help people struggling with the PROD builds.

**Comment by kafeltz** [comment] 2017-02-02 12:19
@Nickersona In fact the `../` did fix for me. But I'm in devel mode and got that error somewhere else.

**Comment by animesh10** [comment] 2017-02-02 19:47
@Nickersona : Thanks for looking into the issue and providing a fix.
@kafeltz : The error was only present in Prod builds, where else were you seeing the error ?

**Comment by darkbls** [comment] 2017-02-10 10:41
@Nickersona same problem here, and same solution. Thank you

**Comment by jshado1** [comment] 2017-02-16 23:18
Note that with the surprise introduction of `src/`, `client/` and `server/` are now a level deeper (inside `src/`), so that `../` needs to go up an additional level: `../..`

**Comment by kirill-konshin** [comment] 2017-03-02 00:20
Adding `../..` fixed the issue for me too.

**Comment by animesh10** [comment] 2017-04-04 22:39
should be fixed after: https://github.com/electrode-io/electrode/pull/224

**Closed** 2017-06-24 06:27 UTC
Labels: answered, bug
