### ISSUE TITLE
Webpack modules resolve order

### ISSUE THREAD

**Issue by jmcriffey** [electrode-io/electrode#210] opened 2017-02-24 18:15 UTC
I want to open a discussion about the resolve order for webpack. I ran into an issue where there was a folder called `redux` in the `client` folder and `import redux from 'redux';` gave me the client folder's index file instead of the node module. I can see pros and cons each way, but that is a really confusing issue to bump up against. Any thoughts @jchip?

https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app-dev/config/webpack/base.js#L67

**Comment by citelao** [comment] 2017-02-24 18:43
Shouldn't local refs be referenced with local paths (`./redux`) for clarity?

**Comment by jchip** [comment] 2017-02-24 18:44
In the new src/lib mode, `src/client` should never be a candidate for resolving modules, while `src` is, so you can do `import client/xyz`.

**Comment by jmcriffey** [comment] 2017-02-24 19:33
@citelao In my specific case, there was an alias for `~redux` that mapped to `client/redux`. It was a shortcut so you don't end up with `../../../../../../../redux` or something similar. 

That is a good point @jchip, unless you use the `client` node module, then you are in trouble again.

**Comment by aweary** [comment] 2017-02-24 19:36
To be clear, the issue is not that attempts to import the local `client/redux` module were failing (which as you pointed out can be referenced with a relative path). It's that attempts to import the actual `redux` npm package failed because the current resolution order caused it to return `client/redux` not `node_modules/redux`

**Comment by jmcriffey** [comment] 2017-02-24 19:42
Here is an example of how it currently works: 

```js
import redux from 'redux'; //currently imports from ./redux if it exists
```

If you actually wanted to support importing from your project root with no modifiers or aliases, then this is what you want. I am leaning towards that being a rare case, since you would usually just use an alias instead.

**Comment by jchip** [comment] 2017-03-09 00:28
@aweary yes, that's why I don't think `client` should be a location for webpack to resolve modules.   I want only the `src` directory (or the root if not src/lib mode) to be a module resolve location.  So if you want to import something that's under the `client` directory, you have to do `import redux from "client/redux"`.

**Closed** 2017-07-06 21:52 UTC
